### ISSUE TITLE
Change tslint semvar to minor release in package.json

### ISSUE THREAD

**Issue by mtraynham** [palantir/grunt-tslint#22]
It's unlikely this interface has to change among newer releases of tslint, atleast across minor versions.  Can we just change this to always pull the latest minor version?

`^2.3.0-beta`

**Comment by adidahiya** [comment]
good idea. I'll make this change today

**Comment by mtraynham** [comment]
thanks!

**Comment by mtraynham** [comment]
just waiting on a npm publish, then should be good :smile:

**Comment by adidahiya** [comment]
published :)

**Comment by mtraynham** [comment]
Thanks @adidahiya!
