### ISSUE TITLE
peer dependency does not allow installation of tslint@next

### ISSUE THREAD

**Issue by adidahiya** [palantir/grunt-tslint#28]
According to the [node-semver docs](https://github.com/npm/node-semver#caret-ranges-123-025-004), a peer dependency on `^2.4.0` does not accept beta or dev releases of a different `[major, minor, patch]` tuple, in this case `2.5.0-dev.2`.

**Comment by mcsagittarius** [comment]
^this...

"npm install grunt-tslint" gives error: "npm WARN EPEERINVALID grunt-tslint@2.5.0 requires a peer of tslint@>=2.5.0-beta but none was installed."

**Comment by klmdb** [comment]
This issue is still persistent.

**Comment by adidahiya** [comment]
We stopped publishing tslint@next with tslint v5. there's no longer a need to use it since tslint works with typescript@next
