### ISSUE TITLE
Exclude files and directories

### ISSUE THREAD

**Issue by davidleureka** [palantir/grunt-tslint#38]
Is it possible to tell the plugin to exclude certain files and directories? I want to run it on my entire codebase but to ignore directories like `node_modules` and `typings`.

**Comment by blackat** [comment]
Hi @davidleureka ,
I have had to exclude a file names `aliases.ts` where I define namespace aliases and I have done in this way

```json
tslint: {
    "options": {
        "configuration": "tslint.json",
        "rulesDirectory": ["node_modules/tslint-eslint-rules/dist/rules"]
    },
    "files": {
        "src": ["client/app/**/!(aliases).ts"]
    }
}
```

basically you can exclude some patterns from the source files.

I hope it helps.

**Comment by wald-tq** [comment]
you can exclude specific files / directories in grunt tasks like this:

```
tslint: {
    options: {
        configuration: "tslint.json",
        force: true
    },
    all: {
        src: [
            'js/**/*.ts', 
            '!js/typings/**'],     // <- relevant exclude line
    },
```

which would tslint all ts files in `js/` and subdirectories but exclude everything under `js/typings`.

More information see: http://gruntjs.com/configuring-tasks

**Comment by adidahiya** [comment]
closing as this is already supported by grunt
