### ISSUE TITLE
Avoid ">> "  prefix in output

### ISSUE THREAD

**Issue by Flarna** [palantir/grunt-tslint#49]
If I run grunt-tslint as external tool in MSVC I face the problem that all findings are prefixed with ">> " resulting in visual studio is not able to parse the result and jump to the corresponding line.

Is there a way to configure grunt-tslint to skip this ">> " prefix?

**Comment by Flarna** [comment]
In case there is no possibility to configure this at the moment: Could you consider to add an option to configure this via the grunt script? if yes I can prepare a PR.

**Comment by deenairn** [comment]
I've added a [PR](https://github.com/palantir/grunt-tslint/pull/63) which may solve this for you, if it's accepted by Palantir. It does not use the grunt.log.error, which automatically appends the ">>" to the line, instead using grunt.log.writeln in a red color. This should allow the messages to be picked up by VS. (The change only applies to MSBuild output for consistency).
