### ISSUE TITLE
Is --fix option supported?

### ISSUE THREAD

**Issue by RachelSatoyama** [palantir/grunt-tslint#59]
Hi! A quick question - is it possible to use autofixes while running this particular task?
I apologize if it's something simple and obvious it's just that from what I'm see from code it's not something that task supports - but may be I'm just missing something?

**Comment by adidahiya** [comment]
not yet, but @Izzmo is working on a PR for it here! #56

**Comment by RachelSatoyama** [comment]
Thanks @adidahiya next time I'll check out PR beforehand )
